const KEYS={progress:"zav-codelab-progress-v1",drafts:"zav-codelab-drafts-v1"};
const lessons=[
  {id:"judul",icon:"👋",type:"HTML dasar",title:"Buat judul",short:"Kenalan dengan <h1>",description:"HTML memberi tahu browser apa yang harus ditampilkan. Tag <h1> dipakai untuk membuat judul utama.",goal:"Ubah tulisan di dalam <h1> menjadi “Aku Bisa Coding!”.",hint:"Ubah tulisan Halo Dunia. Jangan hapus tanda <h1> dan </h1>.",success:"Judul buatanmu sudah tampil dengan benar.",starter:{html:"<h1>Halo Dunia</h1>\n<p>Ini halaman pertamaku.</p>",css:"body {\n  font-family: Arial, sans-serif;\n  padding: 24px;\n}\n\nh1 {\n  color: #6d4aff;\n}",js:""},check:c=>(/<h1[^>]*>\s*aku bisa coding!?\s*<\/h1>/i).test(c.html)},
  {id:"paragraf",icon:"✍️",type:"HTML dasar",title:"Tulis cerita",short:"Bikin paragraf sendiri",description:"Tag <p> adalah tempat untuk menulis kalimat atau cerita pendek di halaman web.",goal:"Tambahkan paragraf baru yang berisi nama atau hobi kamu.",hint:"Tulis baris baru seperti: <p>Hobiku bermain bola.</p>",success:"Sekarang halamanmu sudah punya cerita sendiri.",starter:{html:"<h1>Tentang Aku</h1>\n<p>Namaku ...</p>\n<!-- Tambahkan paragraf baru di bawah ini -->",css:"body {\n  font-family: Arial, sans-serif;\n  padding: 24px;\n  background: #f4f2ff;\n  color: #25213b;\n}",js:""},check:c=>(c.html.match(/<p(?:\s[^>]*)?>[\s\S]*?<\/p>/gi)||[]).length>=2},
  {id:"warna",icon:"🎨",type:"CSS dasar",title:"Ganti warna",short:"Percantik dengan CSS",description:"CSS mengatur tampilan. color mengubah warna tulisan dan background mengubah warna latar.",goal:"Ubah warna judul dan background menjadi pilihanmu sendiri.",hint:"Buka tab CSS. Ganti #6d4aff dan #fff7d6 dengan warna lain.",success:"Kamu berhasil menjadi desainer halaman web.",starter:{html:"<h1>Dunia Warna</h1>\n<p>Aku sedang belajar CSS.</p>",css:"body {\n  font-family: Arial, sans-serif;\n  padding: 24px;\n  background: #fff7d6;\n}\n\nh1 {\n  color: #6d4aff;\n}",js:""},check:c=>{const colors=c.css.match(/(?:color|background(?:-color)?)\s*:\s*[^;\n}]+/gi)||[];return colors.length>=2&&!/#fff7d6/i.test(c.css)&&!/#6d4aff/i.test(c.css)}},
  {id:"kartu",icon:"🪪",type:"HTML + CSS",title:"Buat kartu",short:"Kenalan dengan class",description:"Class menghubungkan bagian HTML dengan gaya CSS. Satu class bisa mengatur banyak tampilan.",goal:"Buat sudut kartu menjadi bulat dengan border-radius minimal 12px.",hint:"Di bagian .kartu tambahkan: border-radius: 16px;",success:"Kartumu sudah rapi dan punya sudut yang lembut.",starter:{html:"<div class=\"kartu\">\n  <h2>Robot Pintar</h2>\n  <p>Project impianku.</p>\n</div>",css:"body {\n  font-family: Arial, sans-serif;\n  padding: 24px;\n  background: #eaf8ff;\n}\n\n.kartu {\n  padding: 20px;\n  background: white;\n  box-shadow: 0 8px 24px #b9d5e3;\n}",js:""},check:c=>{const r=c.css.match(/border-radius\s*:\s*(\d+)px/i);return Boolean(r&&Number(r[1])>=12&&/class=[\"']kartu[\"']/i.test(c.html))}},
  {id:"tombol",icon:"🖱️",type:"JavaScript dasar",title:"Tombol ajaib",short:"Bikin halaman bereaksi",description:"JavaScript membuat halaman bisa bereaksi. Saat tombol ditekan, kita dapat mengubah tulisan di layar.",goal:"Ubah pesan menjadi “Berhasil! Aku menjalankan JavaScript.”",hint:"Buka tab JavaScript lalu ubah tulisan setelah textContent =.",success:"Tombolmu hidup! Ini interaksi JavaScript pertamamu.",starter:{html:"<h1>Tombol Ajaib</h1>\n<button id=\"tombol\">Klik aku</button>\n<p id=\"pesan\">Belum diklik.</p>",css:"body {\n  font-family: Arial, sans-serif;\n  padding: 24px;\n}\n\nbutton {\n  padding: 12px 18px;\n  border: 0;\n  border-radius: 12px;\n  color: white;\n  background: #6d4aff;\n}",js:"const tombol = document.querySelector('#tombol');\nconst pesan = document.querySelector('#pesan');\n\ntombol.addEventListener('click', () => {\n  pesan.textContent = 'Tombol sudah diklik!';\n});"},check:c=>/addEventListener\s*\(\s*[\"']click[\"']/i.test(c.js)&&/berhasil!\s*aku menjalankan javascript\.?/i.test(c.js)},
  {id:"project",icon:"🚀",type:"Project mini",title:"Profil digital",short:"Gabungkan semuanya",description:"Gabungkan HTML, CSS, dan JavaScript menjadi satu project kecil buatanmu sendiri.",goal:"Ganti nama, hobi, warna kartu, dan pesan tombol.",hint:"HTML untuk isi, CSS untuk warna, dan JavaScript untuk pesan tombol.",success:"Project pertamamu selesai. Kamu resmi menjadi pembuat web pemula!",starter:{html:"<main class=\"profil\">\n  <span>👨‍💻</span>\n  <h1>Nama Kamu</h1>\n  <p>Hobiku adalah ...</p>\n  <button id=\"sapa\">Sapa aku</button>\n  <p id=\"jawaban\"></p>\n</main>",css:"body {\n  display: grid;\n  place-items: center;\n  min-height: 90vh;\n  margin: 0;\n  font-family: Arial, sans-serif;\n  background: #eaf8ff;\n}\n\n.profil {\n  width: 240px;\n  padding: 24px;\n  border-radius: 20px;\n  background: white;\n  text-align: center;\n  box-shadow: 0 12px 30px #b9d5e3;\n}\n\n.profil span { font-size: 48px; }\nbutton {\n  padding: 10px 16px;\n  border: 0;\n  border-radius: 12px;\n  color: white;\n  background: #6d4aff;\n}",js:"document.querySelector('#sapa').addEventListener('click', () => {\n  document.querySelector('#jawaban').textContent = 'Halo dari project pertamaku!';\n});"},check:c=>!/>\s*Nama Kamu\s*</i.test(c.html)&&!/Hobiku adalah \.\.\./i.test(c.html)&&!(/\.profil\s*\{[\s\S]*?background\s*:\s*white/i).test(c.css)&&/addEventListener\s*\(/i.test(c.js)&&!/Halo dari project pertamaku!/i.test(c.js)}
];

const $=s=>document.querySelector(s);
const el={lessonList:$("#lessonList"),missionNumber:$("#missionNumber"),missionType:$("#missionType"),missionTitle:$("#missionTitle"),missionDescription:$("#missionDescription"),missionGoal:$("#missionGoal"),editor:$("#codeEditor"),tabs:[...document.querySelectorAll(".language-tab")],frame:$("#previewFrame"),previewStatus:$("#previewStatus"),feedback:$("#feedback"),progressText:$("#progressText"),progressTrack:$("#progressTrack"),progressFill:$("#progressFill"),progressMessage:$("#progressMessage"),levelBadge:$("#levelBadge"),saveState:$("#saveState"),dialog:$("#successDialog"),successMessage:$("#successMessage"),next:$("#nextLessonButton")};
let lessonIndex=0,language="html",timer,initialized=false;
let completed=read(KEYS.progress,[]),drafts=read(KEYS.drafts,{});

function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{el.saveState.textContent="Penyimpanan tidak tersedia"}}
function code(lesson=lessons[lessonIndex]){return drafts[lesson.id]||{...lesson.starter}}
function save(){if(!initialized)return;const current=code();current[language]=el.editor.value;drafts[lessons[lessonIndex].id]=current;write(KEYS.drafts,drafts);el.saveState.textContent="Tersimpan di HP"}
function scheduleSave(){el.saveState.textContent="Menyimpan…";clearTimeout(timer);timer=setTimeout(save,250)}

function renderLessons(){el.lessonList.innerHTML=lessons.map((l,i)=>`<button class="lesson-button ${i===lessonIndex?"active":""}" type="button" data-lesson="${i}" aria-current="${i===lessonIndex?"step":"false"}"><span class="lesson-icon" aria-hidden="true">${l.icon}</span><span class="lesson-label"><strong>${i+1}. ${l.title}</strong><small>${l.short}</small></span><span class="lesson-check" aria-label="${completed.includes(l.id)?"Sudah selesai":"Belum selesai"}">${completed.includes(l.id)?"✓":""}</span></button>`).join("")}
function updateProgress(){const count=lessons.filter(l=>completed.includes(l.id)).length,pct=Math.round(count/lessons.length*100);el.progressText.textContent=`${count} dari ${lessons.length} misi`;el.progressFill.style.width=`${pct}%`;el.progressTrack.setAttribute("aria-valuenow",String(pct));if(count===lessons.length){el.levelBadge.textContent="Creator";el.progressMessage.textContent="Semua misi selesai. Kamu sudah punya project sendiri!"}else if(count>=3){el.levelBadge.textContent="Penjelajah";el.progressMessage.textContent=`${lessons.length-count} misi lagi menuju project pertamamu.`}else{el.levelBadge.textContent="Pemula";el.progressMessage.textContent=count?"Lanjutkan. Setiap misi membuka kemampuan baru.":"Selesaikan satu misi untuk mendapat bintang pertama."}}

function setLanguage(next){save();language=next;el.tabs.forEach(t=>{const active=t.dataset.language===next;t.classList.toggle("active",active);t.setAttribute("aria-selected",String(active))});el.editor.value=code()[next];el.editor.setAttribute("aria-label",`Editor ${next==="js"?"JavaScript":next.toUpperCase()}`)}
function selectLesson(index,scroll=false){save();lessonIndex=index;language="html";const l=lessons[index];el.missionNumber.textContent=String(index+1).padStart(2,"0");el.missionType.textContent=l.type;el.missionTitle.textContent=l.title;el.missionDescription.textContent=l.description;el.missionGoal.textContent=l.goal;el.feedback.className="feedback";el.feedback.textContent="Siap. Ubah kode lalu tekan Jalankan.";el.previewStatus.textContent="Belum dijalankan";setLanguage("html");renderLessons();run();if(scroll)$(".workspace").scrollIntoView({behavior:"smooth",block:"start"})}
function previewDocument(c){const js=c.js.replace(/<\/script/gi,"<\\/script");return `<!doctype html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${c.css}</style></head><body>${c.html}<script>window.addEventListener('error',e=>parent.postMessage({type:'zav-error',message:e.message},'*'));${js};parent.postMessage({type:'zav-ready'},'*');<\/script></body></html>`}
function run(){save();el.previewStatus.textContent="Menjalankan…";el.feedback.className="feedback";el.feedback.textContent="Kode dijalankan. Lihat hasilnya di panel sebelah atau bawah.";el.frame.srcdoc=previewDocument(code())}
function reset(){if(!confirm("Kembalikan kode misi ini ke contoh awal?"))return;const l=lessons[lessonIndex];drafts[l.id]={...l.starter};write(KEYS.drafts,drafts);el.editor.value=drafts[l.id][language];el.feedback.className="feedback";el.feedback.textContent="Kode kembali ke contoh awal.";run()}
function check(){save();const l=lessons[lessonIndex];if(!l.check(code(l))){el.feedback.className="feedback error";el.feedback.textContent=`Belum pas. ${l.hint}`;el.editor.focus();return}if(!completed.includes(l.id)){completed.push(l.id);write(KEYS.progress,completed)}renderLessons();updateProgress();el.feedback.className="feedback success";el.feedback.textContent="✓ Misi berhasil diselesaikan!";el.successMessage.textContent=l.success;el.next.textContent=lessonIndex===lessons.length-1?"Lihat dari awal":"Misi berikutnya";el.dialog.showModal()}
function insert(symbol){const a=el.editor.selectionStart,b=el.editor.selectionEnd;el.editor.setRangeText(symbol,a,b,"end");el.editor.focus();scheduleSave()}

el.lessonList.addEventListener("click",e=>{const b=e.target.closest("[data-lesson]");if(b)selectLesson(Number(b.dataset.lesson),true)});
el.tabs.forEach(t=>t.addEventListener("click",()=>setLanguage(t.dataset.language)));
$(".symbol-tools").addEventListener("click",e=>{const b=e.target.closest("[data-insert]");if(b)insert(b.dataset.insert)});
el.editor.addEventListener("input",scheduleSave);el.editor.addEventListener("keydown",e=>{if(e.key==="Tab"){e.preventDefault();insert("  ")}});
$("#runButton").addEventListener("click",run);$("#hintButton").addEventListener("click",()=>{el.feedback.className="feedback";el.feedback.textContent=`💡 ${lessons[lessonIndex].hint}`});$("#resetButton").addEventListener("click",reset);$("#completeButton").addEventListener("click",check);
el.next.addEventListener("click",()=>{el.dialog.close();selectLesson((lessonIndex+1)%lessons.length,true)});$("#closeDialogButton").addEventListener("click",()=>el.dialog.close());
window.addEventListener("message",e=>{if(e.source!==el.frame.contentWindow||!e.data)return;if(e.data.type==="zav-error"){el.previewStatus.textContent="Ada error";el.feedback.className="feedback error";el.feedback.textContent=`JavaScript bilang: ${e.data.message||"Ada kode yang belum tepat."}`}if(e.data.type==="zav-ready")el.previewStatus.textContent="Berhasil tampil"});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
renderLessons();updateProgress();selectLesson(0);initialized=true;
